### ISSUE TITLE
Content-coding

### ISSUE THREAD

**Issue by ektrah** [core-wg/corrclar#8]
Errata ID: [4954](https://www.rfc-editor.org/errata/eid4954)
Type: Editorial
Reported By: Klaus Hartke
Date Reported: 2017-02-28

[Section 12.3](https://tools.ietf.org/html/rfc7252#section-12.3) says/should say:

```diff
-CoAP does not include a separate way to convey content-encoding
+CoAP does not include a separate way to convey content-coding
 information with a request or response, and for that reason the
-content-encoding is also specified for each identifier (if any).  If
-multiple content-encodings will be used with a media type, then a
+content-coding is also specified for each identifier (if any).  If
+multiple content-codings will be used with a media type, then a
 separate Content-Format identifier for each is to be registered.
 Similarly, other parameters related to an Internet media type, such
 as level, can be defined for a CoAP Content-Format entry.

-+--------------------------+----------+----+------------------------+
-| Media type               | Encoding | ID | Reference              |
-+--------------------------+----------+----+------------------------+
++--------------------------+----------------+----+------------------+
+| Media type               | Content coding | ID | Reference        |
++--------------------------+----------------+----+------------------+
```

A CoAP Content-Format is the combination of an Internet Media Type with an HTTP Content Coding, as correctly explained in the first paragraphs of Section 12.3. However, the next paragraph (the original text above) incorrectly uses the term "content-encoding". The correct term is "content-coding", as shown in the corrected text.

Examples for _valid_ CoAP Content-Format registrations:

- media type "text/plain; charset=iso-8859-1" with content-coding "deflate"

- media type "image/png" with content-coding "" (no content-coding)

- media type "image/png" with content-coding "identity" (same as previous, no content-coding)

- media type "application/example+xml" with content-coding "exi"

Examples for _invalid_ CoAP Content-Format registrations:

- media type "application/coap-group+json" with content-coding "UTF-8" (UTF-8 is a character encoding, not a content-coding; should be media type "application/coap-group+json; charset=utf-8" with content-coding "identity")

- media type "audio/opus" with content-coding "identity" ("audio/opus" has a required parameter "rate"; should be media type "audio/opus; rate=48000" with content-coding "identity")

- media type "application/example+xml" with content-coding "identity, exi" (too many content-codings; should be media type "application/example+xml" with content-coding "identity" and, separately, media type "application/example+xml" with content-coding "exi")

- media type "application/example+exi" with content-coding "identity" ("+exi" is not a registered structured syntax suffix at the time of writing of this erratum)

- media type "video/ogg" with content-coding "exi" (EXI is a content-coding for XML information)

**Comment by cabo** [comment]
More recently, with the terminology established in RFC 9193, we probably want to change the heading "Media-Type" to "Content-Type" as well.

draft-ietf-core-problem-details says:

> In the registry as defined by {{Section 12.3 of -coap}} at the time of
writing, the column "Content-Type" is called "Media type" and the
column "Content Coding" is called "Encoding". [^remove]
